import './globals.scss'
import { Blinker } from 'next/font/google'
import Navbar from "../components/navbar.js"

const blinker = Blinker({ subsets: ['latin'], weight:'400' })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={blinker.className}>
        <Navbar/>
        {children}
      </body>
    </html>
  )
}
